name: Deploy main to Fly
on:
  push:
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup flyctl
        uses: harrissondutra/API_Car_Sale/setup-flyctl@main

      - name: Deploy
        run: flyctl deploy
